import React from "react";
import OpthalmologyIOPComponent from "./OpthalmologyIOPComponent";
import OpthalmologyVAComponent from "./OpthalmologyVAComponent";

export default function OpthalmologyVA({
  handle_oculus_sinister_sphere_auto_refraction,
  oculus_sinister_sphere_auto_refraction,
  handle_oculus_sinister_cylinder_auto_refraction,
  oculus_sinister_cylinder_auto_refraction,
  handle_oculus_sinister_axis_auto_refraction,
  oculus_sinister_axis_auto_refraction,
  handle_oculus_sinister_k1,
  oculus_sinister_k1,
  handle_oculus_sinister_k1_axis,
  oculus_sinister_k1_axis,
  handle_oculus_sinister_k2,
  oculus_sinister_k2,
  handle_oculus_sinister_k2_axis,
  oculus_sinister_k2_axis,
  handle_oculus_sinister_corneal_astigmatism,
  oculus_sinister_corneal_astigmatism,
  handle_oculus_sinister_ucva,
  oculus_sinister_ucva,
  handle_oculus_sinister_pinhole,
  oculus_sinister_pinhole,
  handle_oculus_sinister_visual_acuity_old,
  oculus_sinister_visual_acuity_old,
  handle_oculus_sinister_sphere_old,
  oculus_sinister_sphere_old,
  handle_oculus_sinister_axis_old,
  oculus_sinister_axis_old,
  handle_oculus_sinister_cylinder_old,
  oculus_sinister_cylinder_old,
  handle_oculus_sinister_visual_acuity_manifest_refraction,
  oculus_sinister_visual_acuity_manifest_refraction,
  handle_oculus_sinister_sphere_manifest_refraction,
  oculus_sinister_sphere_manifest_refraction,
  handle_oculus_sinister_cylinder_manifest_refraction,
  oculus_sinister_cylinder_manifest_refraction,
  handle_oculus_sinister_axis_manifest_refraction,
  oculus_sinister_axis_manifest_refraction,
  handle_oculus_sinister_visual_acuity_cyclorefraction,
  oculus_sinister_visual_acuity_cyclorefraction,
  handle_oculus_sinister_sphere_cyclorefraction,
  oculus_sinister_sphere_cyclorefraction,
  handle_oculus_sinister_cylinder_cyclorefraction,
  oculus_sinister_cylinder_cyclorefraction,
  handle_oculus_sinister_axis_cyclorefraction,
  oculus_sinister_axis_cyclorefraction,
  handle_oculus_sinister_near,
  oculus_sinister_near,
  handle_oculus_dextrus_sphere_auto_refraction,
  oculus_dextrus_sphere_auto_refraction,
  handle_oculus_dextrus_cylinder_auto_refraction,
  oculus_dextrus_cylinder_auto_refraction,
  handle_oculus_dextrus_axis_auto_refraction,
  oculus_dextrus_axis_auto_refraction,
  handle_oculus_dextrus_k1,
  oculus_dextrus_k1,
  handle_oculus_dextrus_k1_axis,
  oculus_dextrus_k1_axis,
  handle_oculus_dextrus_k2,
  oculus_dextrus_k2,
  handle_oculus_dextrus_k2_axis,
  oculus_dextrus_k2_axis,
  handle_oculus_dextrus_corneal_astigmatism,
  oculus_dextrus_corneal_astigmatism,
  handle_oculus_dextrus_ucva,
  oculus_dextrus_ucva,
  handle_oculus_dextrus_pinhole,
  oculus_dextrus_pinhole,
  handle_oculus_dextrus_visual_acuity_old,
  oculus_dextrus_visual_acuity_old,
  handle_oculus_dextrus_axis_old,
  oculus_dextrus_axis_old,
  handle_oculus_dextrus_sphere_old,
  oculus_dextrus_sphere_old,
  handle_oculus_dextrus_cylinder_old,
  oculus_dextrus_cylinder_old,
  handle_oculus_dextrus_visual_acuity_manifest_refraction,
  oculus_dextrus_visual_acuity_manifest_refraction,
  handle_oculus_dextrus_sphere_manifest_refraction,
  oculus_dextrus_sphere_manifest_refraction,
  handle_oculus_dextrus_cylinder_manifest_refraction,
  oculus_dextrus_cylinder_manifest_refraction,
  handle_oculus_dextrus_axis_manifest_refraction,
  oculus_dextrus_axis_manifest_refraction,
  handle_oculus_dextrus_visual_acuity_cyclorefraction,
  oculus_dextrus_visual_acuity_cyclorefraction,
  handle_oculus_dextrus_sphere_cyclorefraction,
  oculus_dextrus_sphere_cyclorefraction,
  handle_oculus_dextrus_cylinder_cyclorefraction,
  oculus_dextrus_cylinder_cyclorefraction,
  handle_oculus_dextrus_axis_cyclorefraction,
  oculus_dextrus_axis_cyclorefraction,
  handle_oculus_dextrus_near,
  oculus_dextrus_near,
  handle_oculus_ipd,
  oculus_ipd,
  handle_oculus_sinister_iop_airpuff,
  oculus_sinister_iop_airpuff,
  handle_oculus_sinister_iop_applantation,
  oculus_sinister_iop_applantation,
  handle_oculus_sinister_iop_other,
  oculus_sinister_iop_other,
  handle_oculus_dextrus_iop_airpuff,
  oculus_dextrus_iop_airpuff,
  handle_oculus_dextrus_iop_applantation,
  oculus_dextrus_iop_applantation,
  handle_oculus_dextrus_iop_other,
  oculus_dextrus_iop_other,
}) {
  return (
    <div className="row p-0 m-0 pt-5 mt-4 pb-5 mb-5">
      <div className="col-12 pb-3">
        <div className="row justify-content-center">
          <div className="col-6">
            <OpthalmologyVAComponent
              eye={"OD"}
              handle_sphere_auto_refraction={
                handle_oculus_dextrus_sphere_auto_refraction
              }
              sphere_auto_refraction={oculus_dextrus_sphere_auto_refraction}
              handle_cylinder_auto_refraction={
                handle_oculus_dextrus_cylinder_auto_refraction
              }
              cylinder_auto_refraction={oculus_dextrus_cylinder_auto_refraction}
              handle_axis_auto_refraction={
                handle_oculus_dextrus_axis_auto_refraction
              }
              axis_auto_refraction={oculus_dextrus_axis_auto_refraction}
              handle_k1={handle_oculus_dextrus_k1}
              k1={oculus_dextrus_k1}
              handle_k1_axis={handle_oculus_dextrus_k1_axis}
              k1_axis={oculus_dextrus_k1_axis}
              handle_k2={handle_oculus_dextrus_k2}
              k2={oculus_dextrus_k2}
              handle_k2_axis={handle_oculus_dextrus_k2_axis}
              k2_axis={oculus_dextrus_k2_axis}
              handle_corneal_astigmatism={
                handle_oculus_dextrus_corneal_astigmatism
              }
              corneal_astigmatism={oculus_dextrus_corneal_astigmatism}
              handle_ucva={handle_oculus_dextrus_ucva}
              ucva={oculus_dextrus_ucva}
              handle_pinhole={handle_oculus_dextrus_pinhole}
              pinhole={oculus_dextrus_pinhole}
              handle_visual_acuity_old={handle_oculus_dextrus_visual_acuity_old}
              visual_acuity_old={oculus_dextrus_visual_acuity_old}
              handle_sphere_old={handle_oculus_dextrus_axis_old}
              sphere_old={oculus_dextrus_axis_old}
              handle_cylinder_old={handle_oculus_dextrus_sphere_old}
              cylinder_old={oculus_dextrus_sphere_old}
              handle_axis_old={handle_oculus_dextrus_cylinder_old}
              axis_old={oculus_dextrus_cylinder_old}
              handle_visual_acuity_manifest_refraction={
                handle_oculus_dextrus_visual_acuity_manifest_refraction
              }
              visual_acuity_manifest_refraction={
                oculus_dextrus_visual_acuity_manifest_refraction
              }
              handle_sphere_manifest_refraction={
                handle_oculus_dextrus_sphere_manifest_refraction
              }
              sphere_manifest_refraction={
                oculus_dextrus_sphere_manifest_refraction
              }
              handle_cylinder_manifest_refraction={
                handle_oculus_dextrus_cylinder_manifest_refraction
              }
              cylinder_manifest_refraction={
                oculus_dextrus_cylinder_manifest_refraction
              }
              handle_axis_manifest_refraction={
                handle_oculus_dextrus_axis_manifest_refraction
              }
              axis_manifest_refraction={oculus_dextrus_axis_manifest_refraction}
              handle_visual_acuity_cyclorefraction={
                handle_oculus_dextrus_visual_acuity_cyclorefraction
              }
              visual_acuity_cyclorefraction={
                oculus_dextrus_visual_acuity_cyclorefraction
              }
              handle_sphere_cyclorefraction={
                handle_oculus_dextrus_sphere_cyclorefraction
              }
              sphere_cyclorefraction={oculus_dextrus_sphere_cyclorefraction}
              handle_cylinder_cyclorefraction={
                handle_oculus_dextrus_cylinder_cyclorefraction
              }
              cylinder_cyclorefraction={oculus_dextrus_cylinder_cyclorefraction}
              handle_axis_cyclorefraction={
                handle_oculus_dextrus_axis_cyclorefraction
              }
              axis_cyclorefraction={oculus_dextrus_axis_cyclorefraction}
              handle_near={handle_oculus_dextrus_near}
              near={oculus_dextrus_near}
            />
          </div>
          <div className="col-6 opthalmology-border-va">
            <OpthalmologyVAComponent
              eye={"OS"}
              handle_sphere_auto_refraction={
                handle_oculus_sinister_sphere_auto_refraction
              }
              sphere_auto_refraction={oculus_sinister_sphere_auto_refraction}
              handle_cylinder_auto_refraction={
                handle_oculus_sinister_cylinder_auto_refraction
              }
              cylinder_auto_refraction={
                oculus_sinister_cylinder_auto_refraction
              }
              handle_axis_auto_refraction={
                handle_oculus_sinister_axis_auto_refraction
              }
              axis_auto_refraction={oculus_sinister_axis_auto_refraction}
              handle_k1={handle_oculus_sinister_k1}
              k1={oculus_sinister_k1}
              handle_k1_axis={handle_oculus_sinister_k1_axis}
              k1_axis={oculus_sinister_k1_axis}
              handle_k2={handle_oculus_sinister_k2}
              k2={oculus_sinister_k2}
              handle_k2_axis={handle_oculus_sinister_k2_axis}
              k2_axis={oculus_sinister_k2_axis}
              handle_corneal_astigmatism={
                handle_oculus_sinister_corneal_astigmatism
              }
              corneal_astigmatism={oculus_sinister_corneal_astigmatism}
              handle_ucva={handle_oculus_sinister_ucva}
              ucva={oculus_sinister_ucva}
              handle_pinhole={handle_oculus_sinister_pinhole}
              pinhole={oculus_sinister_pinhole}
              handle_visual_acuity_old={
                handle_oculus_sinister_visual_acuity_old
              }
              visual_acuity_old={oculus_sinister_visual_acuity_old}
              handle_sphere_old={handle_oculus_sinister_sphere_old}
              sphere_old={oculus_sinister_sphere_old}
              handle_cylinder_old={handle_oculus_sinister_cylinder_old}
              cylinder_old={oculus_sinister_cylinder_old}
              handle_axis_old={handle_oculus_sinister_axis_old}
              axis_old={oculus_sinister_axis_old}
              handle_visual_acuity_manifest_refraction={
                handle_oculus_sinister_visual_acuity_manifest_refraction
              }
              visual_acuity_manifest_refraction={
                oculus_sinister_visual_acuity_manifest_refraction
              }
              handle_sphere_manifest_refraction={
                handle_oculus_sinister_sphere_manifest_refraction
              }
              sphere_manifest_refraction={
                oculus_sinister_sphere_manifest_refraction
              }
              handle_cylinder_manifest_refraction={
                handle_oculus_sinister_cylinder_manifest_refraction
              }
              cylinder_manifest_refraction={
                oculus_sinister_cylinder_manifest_refraction
              }
              handle_axis_manifest_refraction={
                handle_oculus_sinister_axis_manifest_refraction
              }
              axis_manifest_refraction={
                oculus_sinister_axis_manifest_refraction
              }
              handle_visual_acuity_cyclorefraction={
                handle_oculus_sinister_visual_acuity_cyclorefraction
              }
              visual_acuity_cyclorefraction={
                oculus_sinister_visual_acuity_cyclorefraction
              }
              handle_sphere_cyclorefraction={
                handle_oculus_sinister_sphere_cyclorefraction
              }
              sphere_cyclorefraction={oculus_sinister_sphere_cyclorefraction}
              handle_cylinder_cyclorefraction={
                handle_oculus_sinister_cylinder_cyclorefraction
              }
              cylinder_cyclorefraction={
                oculus_sinister_cylinder_cyclorefraction
              }
              handle_axis_cyclorefraction={
                handle_oculus_sinister_axis_cyclorefraction
              }
              axis_cyclorefraction={oculus_sinister_axis_cyclorefraction}
              handle_near={handle_oculus_sinister_near}
              near={oculus_sinister_near}
            />
          </div>
        </div>
      </div>
      <div className="col-2 offset-5 pb-2">
        <div className="row">
          <label
            htmlFor="ipd"
            className="col-6 col-form-label mb-2 opthalmology-font-size text-center"
          >
            IPD
          </label>
          <div className="col-6 pt-2">
            <input
              type="text"
              className="form-control form-background"
              onChange={handle_oculus_ipd}
              value={oculus_ipd}
            />
          </div>
        </div>
      </div>
      <div className="col-12 mb-5 pb-5">
        <div className="row justify-content-center">
          <div className="col-6">
            <OpthalmologyIOPComponent
              handle_iop_airpuff={handle_oculus_dextrus_iop_airpuff}
              iop_airpuff={oculus_dextrus_iop_airpuff}
              handle_iop_applantation={handle_oculus_dextrus_iop_applantation}
              iop_applantation={oculus_dextrus_iop_applantation}
              handle_iop_other={handle_oculus_dextrus_iop_other}
              iop_other={oculus_dextrus_iop_other}
            />
          </div>
          <div className="col-6 opthalmology-border-va">
            <OpthalmologyIOPComponent
              handle_iop_airpuff={handle_oculus_sinister_iop_airpuff}
              iop_airpuff={oculus_sinister_iop_airpuff}
              handle_iop_applantation={handle_oculus_sinister_iop_applantation}
              iop_applantation={oculus_sinister_iop_applantation}
              handle_iop_other={handle_oculus_sinister_iop_other}
              iop_other={oculus_sinister_iop_other}
            />
          </div>
        </div>
      </div>
    </div>
  );
}
